/**
 * ebook manager (ebmgr) App
 * ebook manager API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EbookManagerEbmgrApp);
  }
}(this, function(expect, EbookManagerEbmgrApp) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EbookManagerEbmgrApp.Book();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Book', function() {
    it('should create an instance of Book', function() {
      // uncomment below and update the code to test Book
      //var instane = new EbookManagerEbmgrApp.Book();
      //expect(instance).to.be.a(EbookManagerEbmgrApp.Book);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new EbookManagerEbmgrApp.Book();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instane = new EbookManagerEbmgrApp.Book();
      //expect(instance).to.be();
    });

  });

}));
