/**
 * ebook manager (ebmgr) App
 * ebook manager API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Book model module.
* @module model/Book
* @version 0.1.0
*/
export default class Book {
    /**
    * Constructs a new <code>Book</code>.
    * @alias module:model/Book
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Book</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Book} obj Optional instance to populate.
    * @return {module:model/Book} The populated <code>Book</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Book();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
        }
        return obj;
    }

    /**
    * name of book
    * @member {String} name
    */
    name = undefined;
    /**
    * virtualized path of book
    * @member {String} path
    */
    path = undefined;




}
